In [1]:
import pandas as pd
import os

mainpath = "C:/Users/guill/Documents/Universidad/PlataformaRefugiados/NAUTIA/DesarrolloPy/DataSetOriginales"
filename = "Shimelba_HostCommunity_Survey_results.csv"
fullpath = os.path.join(mainpath, filename)

data = pd.read_csv(fullpath)

def dfFix(df,col1,col2):
    result = df
    x = result.columns.get_loc(col1)
    result.drop(result.columns[:x],axis = 1, inplace = True)
    y = result.columns.get_loc(col2)
    result.drop(result.columns[y+1:],axis = 1, inplace = True)
    return result

def mkCSV(df,fileName):
    df.reset_index().to_csv('DataSetFinales/'+fileName,header = True, index=False)

    

data.set_index("group_lj1dr54:refugee_community",inplace=True)

dfCommunity = data.loc['community'].copy()
dfCommunity = dfFix(dfCommunity,"group_lj1dr54:age","group_lj1dr54:_1_5_Choose_the_ethnic_group_o")
mkCSV(dfCommunity,"archivoCommunity.csv")

dfCamp = data.loc['refugee'].copy()
dfCamp = dfFix(dfCamp,"group_lj1dr54:age","group_lj1dr54:_1_5_Choose_the_ethnic_group_o")
mkCSV(dfCamp,"archivoShimelba.csv")

In [2]:
data.head(0)

Empty DataFrame
Columns: [group_lj1dr54:female_male, group_lj1dr54:age, group_lj1dr54:_4_Choose_the_name_of_the_host, group_lj1dr54:Specify_the_name_of_the_host_community, group_lj1dr54:_1_5_Choose_the_ethnic_group_o, group_lj1dr54:Write_the_other_ethnic_group, group_on1ls06:_2_1_Are_you_the_fam_ly_head_of_your_home, group_on1ls06:number_people, group_on1ls06:number_adults, group_on1ls06:number_children, group_ab8oh18:_3_1_Who_cooks_in_your_home, group_ab8oh18:Who_are_you, group_ab8oh18:_3_2_Where_do_you_cook, group_ab8oh18:fuel_for_cooking, group_ab8oh18:fuel_for_cooking_other, group_ab8oh18:kind_food, group_ab8oh18:Specify_other_kind_o_food_you_usually_eat, group_jt4im96:water_supply, group_jt4im96:water_supply_hours, group_jt4im96:_4_3_What_time_of_da_ve_the_water_service, group_jt4im96:water_collect, group_jt4im96:water_cost, group_ta0zp37:Do_you_have_electricity_servic, group_ta0zp37:Is_your_house_to_connected_to, group_ta0zp37:Specify_other_generator, group_ta0zp37:_5_3_What_is_your_el_our_electricity_bill, group_ta0zp37:voltage_change, group_ta0zp37:_5_5_How_much_money_vice_ET_Birr_month, group_ta0zp37:_5_6_How_many_hours_electricity_service, group_ta0zp37:household_appliances_access, group_ta0zp37:Specify_other_electric_equipment, group_ta0zp37:household_appliances_hours, group_ta0zp37:How_many_hours_do_yo_pment_in_the_MORNING, group_ta0zp37:How_many_hours_do_yo_ent_in_the_AFTERNOON, group_ta0zp37:How_many_hours_do_yo_c_equipment_at_NIGHT, group_ta0zp37:What_kind_of_household_applian, group_ta0zp37:Specify_other_elect_the_most_important, group_ge3fs27:_6_1_Have_you_performed_any_im, group_ge3fs27:kind_improvements, group_ge3fs27:kind_improvements_other, group_ge3fs27:number_rooms, group_ge3fs27:_6_4_Do_you_have_an_oom_designed_to_cook, group_ge3fs27:_6_5_Do_you_use_, group_ge3fs27:_6_6_Do_you_use, group_ge3fs27:habitability_conditions, group_on8wi24:sources_incomes, group_on8wi24:Specify_the_work_activity, group_on8wi24:Specify_others_incomes_sources, group_on8wi24:incomes, group_on8wi24:invest, _8_Do_you_want_to_ad_during_the_interview, _9_Could_you_tell_me_iewee_agrees_to_this, meta:instanceID]
Index: []

[0 rows x 53 columns]

In [3]:
dfToAdd = data

In [4]:
dfToAdd.shape

(307, 53)

In [5]:
x = dfToAdd.columns.get_loc("group_on1ls06:number_people")
dfToAdd.drop(dfToAdd.columns[:x],axis = 1, inplace = True)
dfToAdd.drop(dfToAdd.columns[x+1:],axis = 1, inplace = True)

In [6]:
dfToAdd.shape

(307, 8)

In [7]:
dfToAdd = dfToAdd.loc['community'].copy()

In [8]:
dfToAdd.shape

(146, 8)

In [9]:
dfCommunity.shape

(146, 4)

In [10]:
dfFinalCommunity = pd.concat([dfCommunity,dfToAdd],axis = 1)

In [11]:
data2 = pd.read_csv("C:/Users/guill/Documents/Universidad/PlataformaRefugiados/NAUTIA/DesarrolloPy/DataSetOriginales/Bibliography_111019.csv",sep = ";")

In [12]:
data2

,Unnamed: 0,GENERAL INFORMATION - COUNTRY LEVEL,Unnamed: 2,Unnamed: 3
0,1,Population,Host community's country,Refugees' country
1,"1,1",Country's name,Etiopia,Eritrea
2,"1,2",Number of inhabitants (#),105000000,4475000
3,1.2.1,"Men, younger than 5 years (%)",20,10
4,1.2.2,Women between 5-17 years (%),10,20
5,1.2.3,"Men, between 5-17 years (%)",10,20
6,1.2.4,Women between18-59 years (%),10,10
7,1.2.5,Men between 18-59 years(%),10,10
8,1.2.6,Women older than 60 years (%),10,10
9,1.2.7,Women youngere than 5 years (%),20,10
10,1.2.8,"Men, older than 60 years (%)",10,10
11,"1,3",Total population,NaN,NaN
12,1.3.1,Total children younger than 5 years (%),40,20
13,1.3.2,Total population between 5-17 years (%),20,40
14,1.3.3,Total population between 18 to 59 years (%),20,20
15,1.3.4,Total population 60 aÃ±os (%),20,20
16,"1,4",Growth rate of populatoin (%),34,45
17,"1,5",Refugee population (%),5,4
18,"1,6",Human development index (points),3,3
19,"1,7",Life expentancy at birth (years),65,60
20,2,Culture,NaN,NaN
21,"2,1",Ethnic groups,NaN,NaN
22,2.1.1,Ethnich group 1,grupo 1,grupo 2
23,2.1.2,Ethnich group 2,grupo 2,NaN
24,2.1.3,Ethnich group 3,NaN,NaN
25,"2,2",Religion,NaN,NaN
26,2.2.1,Religion 1,musulmana,musulmana
27,2.2.2,Religion 2,cristiana,NaN
28,2.2.3,Religion 3,judia,NaN
29,"2,3",Language,NaN,NaN
...,...,...,...,...
161,"27,6",6,NaN,NaN
162,"27,7",7,NaN,NaN
163,28,Private institutions,NaN,NaN
164,"28,1",1,una,otra
165,"28,2",2,NaN,NaN
166,"28,3",3,NaN,NaN
167,"28,4",4,NaN,NaN
168,"28,5",5,NaN,NaN
169,"28,6",6,NaN,NaN
170,29,Non-profit organizations/NGOs,NaN,NaN
171,"29,1",1,una,otra
172,"29,2",2,NaN,NaN
173,"29,3",3,NaN,NaN
174,"29,4",4,NaN,NaN
175,"29,5",5,NaN,NaN
176,"29,6",6,NaN,NaN
177,30,International cooperation agencies,NaN,NaN
178,"30,1",1,una,otra
179,"30,2",2,NaN,NaN
180,"30,3",3,NaN,NaN
181,"30,4",4,NaN,NaN
182,"30,5",5,NaN,NaN
183,"30,6",6,NaN,NaN
184,31,Local representatives/local committees/ local ...,NaN,NaN
185,"31,1",1,una,otra
186,"31,2",2,NaN,NaN
187,"31,3",3,NaN,NaN
188,"31,4",4,NaN,NaN
189,"31,5",5,NaN,NaN
190,"31,6",6,NaN,NaN

In [13]:
data2 = dfFix(data2,"GENERAL INFORMATION - COUNTRY LEVEL","Unnamed: 3")

In [14]:
data2

,GENERAL INFORMATION - COUNTRY LEVEL,Unnamed: 2,Unnamed: 3
0,Population,Host community's country,Refugees' country
1,Country's name,Etiopia,Eritrea
2,Number of inhabitants (#),105000000,4475000
3,"Men, younger than 5 years (%)",20,10
4,Women between 5-17 years (%),10,20
5,"Men, between 5-17 years (%)",10,20
6,Women between18-59 years (%),10,10
7,Men between 18-59 years(%),10,10
8,Women older than 60 years (%),10,10
9,Women youngere than 5 years (%),20,10
10,"Men, older than 60 years (%)",10,10
11,Total population,NaN,NaN
12,Total children younger than 5 years (%),40,20
13,Total population between 5-17 years (%),20,40
14,Total population between 18 to 59 years (%),20,20
15,Total population 60 aÃ±os (%),20,20
16,Growth rate of populatoin (%),34,45
17,Refugee population (%),5,4
18,Human development index (points),3,3
19,Life expentancy at birth (years),65,60
20,Culture,NaN,NaN
21,Ethnic groups,NaN,NaN
22,Ethnich group 1,grupo 1,grupo 2
23,Ethnich group 2,grupo 2,NaN
24,Ethnich group 3,NaN,NaN
25,Religion,NaN,NaN
26,Religion 1,musulmana,musulmana
27,Religion 2,cristiana,NaN
28,Religion 3,judia,NaN
29,Language,NaN,NaN
...,...,...,...
161,6,NaN,NaN
162,7,NaN,NaN
163,Private institutions,NaN,NaN
164,1,una,otra
165,2,NaN,NaN
166,3,NaN,NaN
167,4,NaN,NaN
168,5,NaN,NaN
169,6,NaN,NaN
170,Non-profit organizations/NGOs,NaN,NaN
171,1,una,otra
172,2,NaN,NaN
173,3,NaN,NaN
174,4,NaN,NaN
175,5,NaN,NaN
176,6,NaN,NaN
177,International cooperation agencies,NaN,NaN
178,1,una,otra
179,2,NaN,NaN
180,3,NaN,NaN
181,4,NaN,NaN
182,5,NaN,NaN
183,6,NaN,NaN
184,Local representatives/local committees/ local ...,NaN,NaN
185,1,una,otra
186,2,NaN,NaN
187,3,NaN,NaN
188,4,NaN,NaN
189,5,NaN,NaN
190,6,NaN,NaN

In [15]:
data2.columns = ['GeneralInfo', 'CommunityCountry', 'RefugeeCountry']

In [16]:
data2 = data2.transpose()

In [17]:
data2

,0,1,2,3,4,5,6,7,8,9,...,181,182,183,184,185,186,187,188,189,190
GeneralInfo,Population,Country's name,Number of inhabitants (#),"Men, younger than 5 years (%)",Women between 5-17 years (%),"Men, between 5-17 years (%)",Women between18-59 years (%),Men between 18-59 years(%),Women older than 60 years (%),Women youngere than 5 years (%),...,4,5,6,Local representatives/local committees/ local ...,1,2,3,4,5,6
CommunityCountry,Host community's country,Etiopia,105000000,20,10,10,10,10,10,20,...,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN
RefugeeCountry,Refugees' country,Eritrea,4475000,10,20,20,10,10,10,10,...,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN

In [18]:
data2.columns = data2.iloc[0]

In [25]:
pd.options.display.max_columns = None

In [26]:
data2

GeneralInfo,Population,Country's name,Number of inhabitants (#),"Men, younger than 5 years (%)",Women between 5-17 years (%),"Men, between 5-17 years (%)",Women between18-59 years (%),Men between 18-59 years(%),Women older than 60 years (%),Women youngere than 5 years (%),"Men, older than 60 years (%)",Total population,Total children younger than 5 years (%),Total population between 5-17 years (%),Total population between 18 to 59 years (%),Total population 60 aÃ±os (%),Growth rate of populatoin (%),Refugee population (%),Human development index (points),Life expentancy at birth (years),Culture,Ethnic groups,Ethnich group 1,Ethnich group 2,Ethnich group 3,Religion,Religion 1,Religion 2,Religion 3,Language,Language 1,Language 2,Language 3,Economy and well-being,Population with access to employment,Agriculture (%),Livestock (%),Industry (%),Services (%),Poor people rate (%),Index GINI (points),PIB per cap (USD),Poverty line (USD/day),Local currency,Exchange rate (local currency vs USD),Government,System of governance (choose one),Parliamentary republic,Presidential republic,Syngle-party republic,Parliamentary monarchy,Absolute monarchy,Dictatorship,Another,Territorial and Urbanistic,Location,Urban population (%),Rural population (%),Population density,Urban (inhabitants/hectares),Rural (inhabitants/hectares),Infrastructures,Access to drinking water supply,Total (%),Urban (%),Rural (%),Access to improved sanitation,Total (%),Urban (%),Rural (%),Access to electricity,Total (%),Urban (%),Rural (%),Local electrificy tariff (local currency/kWh),Matrix of electricity generation,Hydropower (%),Diesel generation (%),Gas (%),Coal (%),Solar photovoltaic (%),Wind power (%),Biomass/biofuels (%),High voltage (kV),Low voltage (V),Access to Services,Illiteracy rate (%),Internet access rate (%),Shelter,Slum population rate (%),SPECIFIC INFORMATION - SETTLEMENTS LEVEL,CULTURE IDENTIFICATION,Religion,Religion 1,Religion 2,Religion 3,Language,Language 1,Language 2,Language 3,PHYSICAL AND ENVIRONMENT DATA,Location,Latitude,Longitud,Topography,Upper bound (m),Lower bound (m),FOOD SECURITY,Cause of food insecurity,Cause 1,Cause 2,Cause 3,Affected groups due to food insecurity,Children,Women,Men,Old people,Calories of the typical dish,Pork (200 kcal/100g),Beef 180 kcal/100 g,Chicken: 130 kcal/100 g,Lamp: 125 kcal/100 g,Cereales/grains: 350 kcal/100 g,Legumes: 350 kcal/100 g,Fruits: 50-200 kcal/100 g,Intake (g) - default value 70g-,GENERAL INFORMATION OF REFUGEES SETTLEMENT,Implementation date of the refugee camp (year),Migration reasons,Reason 1,Reason 2,Reason 3,Reason 4,Climate,"Tropical (Write one: Af, Aw or Am)","Dry (Write one: Bsh, Bsk, Bwh or Bwk)","Temperated (Write one: Cdb, Cfc, Csa, Csb, Cfa, Cwa, Cwb)","Continental (Write one: Dfa, Bwa, Dsa or Dfb, Dwb, Dsb)",Temperature,Max (ÂºC),Min (ÂºC),Average (ÂºC),Relative humidity (%),Annual precipitation,Max (mm),Min (mm),Solar irradiance (kW/m2/day),Wind speed,Additional information,Heights of close rivers (r=20km),1,2,3,4,ACTORS (PARTNERS) IDENTIFICATION,Public institutions,1,2,3,4,5,6,7,Private institutions,1,2,3,4,5,6,Non-profit organizations/NGOs,1,2,3,4,5,6,International cooperation agencies,1,2,3,4,5,6,Local representatives/local committees/ local liders,1,2,3,4,5,6
CommunityCountry,Host community's country,Etiopia,105000000,20,10,10,10,10,10,20,10,NaN,40,20,20,20,34,5,3,65,NaN,NaN,grupo 1,grupo 2,NaN,NaN,musulmana,cristiana,judia,NaN,amhÃ¡rico,inglÃ©s,francÃ©s,NaN,NaN,23,20,12,15,45,0.8,12,"1,25",una,12,NaN,NaN,NaN,si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,70,NaN,22,65,NaN,NaN,60,40,20,NaN,60,40,20,NaN,60,40,20,23,NaN,12,23,34,34,23,12,12,443,23,NaN,23,54,NaN,34,NaN,Host community,NaN,musulmana,cristiana,judia,NaN,amhÃ¡rico,inglÃ©s,francÃ©s,Host community,NaN,1Âº2'3'',3Âº2'1'',NaN,150,30,Host community,NaN,uno,dos,NaN,NaN,si,si,si,si,NaN,2,"1,8","1,3","1,25","3,5","3,5",2,70,Host community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Host community,NaN,una,NaN,NaN,NaN,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN
RefugeeCountry,Refugees' country,Eritrea,4475000,10,20,20,10,10,10,10,10,NaN,20,40,20,20,45,4,3,60,NaN,NaN,grupo 2,NaN,NaN,NaN,musulmana,NaN,NaN,NaN,tigriÃ±a,NaN,NaN,NaN,NaN,23,20,12,15,55,0.95,33,"1,25",otra,120,NaN,NaN,NaN,NaN,NaN,NaN,si,NaN,NaN,NaN,NaN,20,80,NaN,35,65,NaN,NaN,40,30,10,NaN,40,30,10,NaN,40,30,10,24,NaN,12,23,34,34,23,12,12,55,45,NaN,45,35,NaN,55,NaN,Refugees,NaN,musulmana,NaN,NaN,NaN,tigriÃ±a,NaN,NaN,Refugees,NaN,3Âº2'1'',1Âº2'3'',NaN,60,0,Refugees,NaN,uno,NaN,NaN,NaN,si,si,si,si,NaN,2,"1,8","1,3","1,25","3,5","3,5",2,70,Refugees,01/10/1990,NaN,una,otra,distinta,NaN,NaN,NaN,si,NaN,NaN,NaN,50,0,30,15,NaN,200,0,123,12,NaN,NaN,30,30,30,NaN,Refugees,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN

In [20]:
data2 = data2.drop(data2.index[0])

In [21]:
dfCommunityCountry = data2.drop(data2.index[1])

In [22]:
dfCommunityCountry.head(1)

GeneralInfo,Population,Country's name,Number of inhabitants (#),"Men, younger than 5 years (%)",Women between 5-17 years (%),"Men, between 5-17 years (%)",Women between18-59 years (%),Men between 18-59 years(%),Women older than 60 years (%),Women youngere than 5 years (%),...,4,5,6,Local representatives/local committees/ local liders,1,2,3,4,5,6
CommunityCountry,Host community's country,Etiopia,105000000,20,10,10,10,10,10,20,...,NaN,NaN,NaN,NaN,una,NaN,NaN,NaN,NaN,NaN

In [23]:
dfRefugeeCountry = data2.drop(data2.index[0])

In [28]:
dfRefugeeCountry

GeneralInfo,Population,Country's name,Number of inhabitants (#),"Men, younger than 5 years (%)",Women between 5-17 years (%),"Men, between 5-17 years (%)",Women between18-59 years (%),Men between 18-59 years(%),Women older than 60 years (%),Women youngere than 5 years (%),"Men, older than 60 years (%)",Total population,Total children younger than 5 years (%),Total population between 5-17 years (%),Total population between 18 to 59 years (%),Total population 60 aÃ±os (%),Growth rate of populatoin (%),Refugee population (%),Human development index (points),Life expentancy at birth (years),Culture,Ethnic groups,Ethnich group 1,Ethnich group 2,Ethnich group 3,Religion,Religion 1,Religion 2,Religion 3,Language,Language 1,Language 2,Language 3,Economy and well-being,Population with access to employment,Agriculture (%),Livestock (%),Industry (%),Services (%),Poor people rate (%),Index GINI (points),PIB per cap (USD),Poverty line (USD/day),Local currency,Exchange rate (local currency vs USD),Government,System of governance (choose one),Parliamentary republic,Presidential republic,Syngle-party republic,Parliamentary monarchy,Absolute monarchy,Dictatorship,Another,Territorial and Urbanistic,Location,Urban population (%),Rural population (%),Population density,Urban (inhabitants/hectares),Rural (inhabitants/hectares),Infrastructures,Access to drinking water supply,Total (%),Urban (%),Rural (%),Access to improved sanitation,Total (%),Urban (%),Rural (%),Access to electricity,Total (%),Urban (%),Rural (%),Local electrificy tariff (local currency/kWh),Matrix of electricity generation,Hydropower (%),Diesel generation (%),Gas (%),Coal (%),Solar photovoltaic (%),Wind power (%),Biomass/biofuels (%),High voltage (kV),Low voltage (V),Access to Services,Illiteracy rate (%),Internet access rate (%),Shelter,Slum population rate (%),SPECIFIC INFORMATION - SETTLEMENTS LEVEL,CULTURE IDENTIFICATION,Religion,Religion 1,Religion 2,Religion 3,Language,Language 1,Language 2,Language 3,PHYSICAL AND ENVIRONMENT DATA,Location,Latitude,Longitud,Topography,Upper bound (m),Lower bound (m),FOOD SECURITY,Cause of food insecurity,Cause 1,Cause 2,Cause 3,Affected groups due to food insecurity,Children,Women,Men,Old people,Calories of the typical dish,Pork (200 kcal/100g),Beef 180 kcal/100 g,Chicken: 130 kcal/100 g,Lamp: 125 kcal/100 g,Cereales/grains: 350 kcal/100 g,Legumes: 350 kcal/100 g,Fruits: 50-200 kcal/100 g,Intake (g) - default value 70g-,GENERAL INFORMATION OF REFUGEES SETTLEMENT,Implementation date of the refugee camp (year),Migration reasons,Reason 1,Reason 2,Reason 3,Reason 4,Climate,"Tropical (Write one: Af, Aw or Am)","Dry (Write one: Bsh, Bsk, Bwh or Bwk)","Temperated (Write one: Cdb, Cfc, Csa, Csb, Cfa, Cwa, Cwb)","Continental (Write one: Dfa, Bwa, Dsa or Dfb, Dwb, Dsb)",Temperature,Max (ÂºC),Min (ÂºC),Average (ÂºC),Relative humidity (%),Annual precipitation,Max (mm),Min (mm),Solar irradiance (kW/m2/day),Wind speed,Additional information,Heights of close rivers (r=20km),1,2,3,4,ACTORS (PARTNERS) IDENTIFICATION,Public institutions,1,2,3,4,5,6,7,Private institutions,1,2,3,4,5,6,Non-profit organizations/NGOs,1,2,3,4,5,6,International cooperation agencies,1,2,3,4,5,6,Local representatives/local committees/ local liders,1,2,3,4,5,6
RefugeeCountry,Refugees' country,Eritrea,4475000,10,20,20,10,10,10,10,10,NaN,20,40,20,20,45,4,3,60,NaN,NaN,grupo 2,NaN,NaN,NaN,musulmana,NaN,NaN,NaN,tigriÃ±a,NaN,NaN,NaN,NaN,23,20,12,15,55,0.95,33,"1,25",otra,120,NaN,NaN,NaN,NaN,NaN,NaN,si,NaN,NaN,NaN,NaN,20,80,NaN,35,65,NaN,NaN,40,30,10,NaN,40,30,10,NaN,40,30,10,24,NaN,12,23,34,34,23,12,12,55,45,NaN,45,35,NaN,55,NaN,Refugees,NaN,musulmana,NaN,NaN,NaN,tigriÃ±a,NaN,NaN,Refugees,NaN,3Âº2'1'',1Âº2'3'',NaN,60,0,Refugees,NaN,uno,NaN,NaN,NaN,si,si,si,si,NaN,2,"1,8","1,3","1,25","3,5","3,5",2,70,Refugees,01/10/1990,NaN,una,otra,distinta,NaN,NaN,NaN,si,NaN,NaN,NaN,50,0,30,15,NaN,200,0,123,12,NaN,NaN,30,30,30,NaN,Refugees,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN,NaN,otra,NaN,NaN,NaN,NaN,NaN

In [29]:
data_Entities = pd.read_csv("C:/Users/guill/Documents/Universidad/PlataformaRefugiados/NAUTIA/DesarrolloPy/DataSetOriginales/NAUTIA_1_0_Entities_Interview_results.csv",sep = ";")

In [33]:
data_Entities

Empty DataFrame
Columns: [start,"end","Type_of_settlement","Type_Host_Community","Identification:Institution_Name","Identification:Contact_person","Identification:Work_Area","GENERAL_INFORMATION:Secondary_movement","GENERAL_INFORMATION:Relationship","GENERAL_INFORMATION:Movement_outside","GENERAL_INFORMATION:Distance","Population:Women:Infants","Population:Women:Childs","Population:Women:Adults","Population:Women:Olders","Population:Men:Infants_001","Population:Men:Childs_001","Population:Men:Adults_001","Population:Men:Olders_001","Fuel_Cost:Main_Fuel","Fuel_Cost:Fuel_Cost_Diesel","Fuel_Cost:Fuel_Cost_Kerosene","Fuel_Cost:Fuel_Cost_Ethanol","Fuel_Cost:Fuel_Cost_Gas_cylder","ENERGY:Electricity_network","ENERGY:Covered_services","ENERGY:Power_failure","ENERGY:Demand_Curve","ENERGY:Street_Light","Urban_Planning_001:Urban_Planning","Urban_Planning_001:Period","Urban_Planning_001:Growth_area","Urban_Planning_001:Forecast","Urban_Planning_001:Land_Managment","Urban_Planning_001:Risk_Managment","Urban_Planning_001:Risk_Identified","Shelter:Plot_Area","Shelter:Plot_Limits","Shelter:Housing_Improvement","Shelter:Total_shelter","Shelter:Cost","Shelter:Shelter_Construction","Shelter:Vulnerable_Area:Vunerable_Area","Enviormental_Issues:Risk:Risk_Flood","Enviormental_Issues:Risk:Risk_dryness","Enviormental_Issues:Risk:Risk_earthquake","Enviormental_Issues:Risk:Risk_storm","Enviormental_Issues:Risk:Risk_plage","Enviormental_Issues:Deforestation","Enviormental_Issues:High_enviormental_value","Enviormental_Issues:Native_Plant","Enviormental_Issues:Native_Crops","Water_table","Sanitation:Personal_hygiene","Sanitation:Excreta","Sanitation:Open_defecation","Sanitation:Type_of_Latrine","Sanitation:Individual_Latrines","Waste_Managment:Waste_Collection","Waste_Managment:Landfill_Details:Location_1","Waste_Managment:Landfill_Details:Location_2","Waste_Managment:Landfill_Details:Adecuate_land","Water:Quality","Water:Treatment","Water:Comsuption","Water:Distribution","Water:Time","Women_Patrol","Education_Issues","Data_Access","Antenna","meta:instanceID"]
Index: []

In [34]:
data_Shelter = pd.read_csv("C:/Users/guill/Documents/Universidad/PlataformaRefugiados/NAUTIA/DesarrolloPy/DataSetOriginales/NAUTIA_1_0_Shelter_results.csv",sep = ";")

In [35]:
data_Shelter

   start,"end","Type_of_setlement","Type_of_Host_Community","Location:Latitude","Location:Longitude","Location:Altitude","Location:Accuracy","Construc_tion_Details:Appropiate_Roof","Construc_tion_Details:Structural_Security","Construc_tion_Details:Resilient","Construc_tion_Details:Ventilation","Construc_tion_Details:Humidity","Construc_tion_Details:Animals","Construc_tion_Details:Thermal_Confort","Construc_tion_Details:Picture_Outside","Construc_tion_Details:Picture_Outside_001","Construc_tion_Details:Picture_Inside","Water_Access","Important_Note","Sanitation_acess","Important_Note_001","Crop_Yard","Important_Note_002","Energy","Important_Note_003","meta:instanceID"
0   2019-11-26 10:19:45.77,"2019-11-26 10:32:26.61...
1   2019-11-26 10:39:55.362,"2019-11-26 10:51:40.2...
2   2019-11-26 10:58:32.712,"2019-11-26 11:08:55.0...
3   2019-11-26 11:17:50.751,"2019-11-26 11:23:00.3...
4   2019-11-26 11:36:32.58,"2019-11-26 11:40:22.21...
5   2019-11-26 11:52:49.454,"2019-11-26 11:58:52.3...
6   2019-11-26 12:23:36.171,"2019-11-26 12:29:10.4...
7   2019-11-26 12:42:27.274,"2019-11-26 12:48:30.6...
8   2019-11-09 12:41:54.174,"2019-11-09 12:49:40.9...
9   2019-11-26 17:40:17.101,"2019-11-26 17:43:28.2...
10  2019-11-26 18:02:33.581,"2019-11-26 18:10:17.9...
11  2019-11-26 18:17:14.501,"2019-11-26 18:22:41.7...
12  2019-11-26 18:31:13.942,"2019-11-26 18:37:10.9...
13  2019-11-26 18:41:50.384,"2019-11-26 18:45:21.5...
14  2019-11-29 18:00:46.229,"2019-11-29 18:04:25.3...
15  2019-11-29 18:24:29.61,"2019-11-29 18:38:11.13...
16  2019-11-29 18:39:56.398,"2019-11-29 18:47:02.5...
17  2019-12-02 18:14:55.526,"2019-12-02 18:23:20.2...
18  2019-11-27 17:42:37.385,"2019-11-27 17:45:46.5...
19  2019-11-27 17:52:46.631,"2019-11-27 18:05:13.6...