In [1]:
import pandas as pd
import os
mainpath = "C:/Users/guill/Documents/Universidad/PlataformaRefugiados/NAUTIA/DesarrolloPy/DataSetOriginales"
filename = "Shimelba_HostCommunity_Survey_results.csv"
fullpath = os.path.join(mainpath, filename)

In [3]:
data = pd.read_csv(fullpath)

In [8]:
data.head(2)

,group_lj1dr54:female_male,group_lj1dr54:age,group_lj1dr54:refugee_community,group_lj1dr54:_4_Choose_the_name_of_the_host,group_lj1dr54:Specify_the_name_of_the_host_community,group_lj1dr54:_1_5_Choose_the_ethnic_group_o,group_lj1dr54:Write_the_other_ethnic_group,group_on1ls06:_2_1_Are_you_the_fam_ly_head_of_your_home,group_on1ls06:number_people,group_on1ls06:number_adults,...,group_ge3fs27:_6_6_Do_you_use,group_ge3fs27:habitability_conditions,group_on8wi24:sources_incomes,group_on8wi24:Specify_the_work_activity,group_on8wi24:Specify_others_incomes_sources,group_on8wi24:incomes,group_on8wi24:invest,_8_Do_you_want_to_ad_during_the_interview,_9_Could_you_tell_me_iewee_agrees_to_this,meta:instanceID
0,female,32,community,shimelba,NaN,tigrinya,NaN,no,5,2,...,none,bad,work_activity,sale_of,NaN,400,"Clothes, food",No,Kidan Teklay,uuid:0498d567-4210-48bd-a20a-75a4c8a7830e
1,female,37,community,shimelba,NaN,tigrinya,NaN,yes,2,1,...,none,good,work_activity,sale_of,NaN,500,Food,No,Tahigas G.maryam,uuid:57514c0a-aff7-4ca2-85ba-0b979b853cec

In [12]:
df = data

In [13]:
for column in df.columns:
    if column == "group_lj1dr54:_4_Choose_the_name_of_the_host":
        x = df.columns.get_loc("group_lj1dr54:_4_Choose_the_name_of_the_host")
    else: 
        if  column == "group_lj1dr54:age":
            y = df.columns.get_loc("group_on1ls06:_2_1_Are_you_the_fam_ly_head_of_your_home")
            
df.drop(df.columns[0:x],axis = 1, inplace = True)
df.drop(df.columns[y-1:],axis = 1, inplace = True)

In [14]:
df.head(2)

,group_lj1dr54:refugee_community,group_lj1dr54:_4_Choose_the_name_of_the_host,group_lj1dr54:Specify_the_name_of_the_host_community,group_lj1dr54:_1_5_Choose_the_ethnic_group_o,group_lj1dr54:Write_the_other_ethnic_group,group_on1ls06:_2_1_Are_you_the_fam_ly_head_of_your_home,group_on1ls06:number_people,group_on1ls06:number_adults
0,community,shimelba,NaN,tigrinya,NaN,no,5,2
1,community,shimelba,NaN,tigrinya,NaN,yes,2,1